"""Page-specific search metadata for localized public pages."""

LOCALIZED_SEO_PAGE_COPY = {
    "ko": {
        "company_benefits_page": (
            "카지노 기업 복리후생 비교 | Casino IN",
            "파라다이스, GKL, 강원랜드, 롯데관광개발 등 카지노 기업의 복지제도, 지원 금액·수준, 비고와 종료 이력을 비교합니다.",
        ),
        "tips.glossary_page": (
            "카지노·경영·재무 용어집 | Casino IN",
            "카지노 운영, 경영관리, 재무, 회계, 투자 분석에 쓰이는 핵심 용어의 영문 표기와 뜻, 쉬운 설명을 찾아봅니다.",
        ),
    },
    "en": {
        "company_benefits_page": (
            "Casino Company Employee Benefits | Casino IN",
            "Compare employee benefit programs, support amounts, notes, and discontinued benefits across major Korean casino companies.",
        ),
        "tips.glossary_page": (
            "Casino, Management and Finance Glossary | Casino IN",
            "Find English terms, definitions, and plain-language explanations for casino operations, management, accounting, finance, and investment analysis.",
        ),
        "notice_board_page": (
            "Notices | Casino IN",
            "Read important Casino IN service announcements, update notes, and operating notices.",
        ),
    },
    "ja": {
        "public_home": ("Casino IN | カジノ産業情報・分析", "韓国と海外のカジノ企業、訪韓客、為替、開示、市場動向、採用、法規制などの産業データをまとめて確認できます。"),
        "casino_industry_page": ("韓国カジノ産業の現況 | Casino IN", "韓国の外国人専用カジノと内国人向け施設について、運営会社、地域分布、売上高、利用者数を比較します。"),
        "casino_visitors_page": ("韓国カジノの年間利用者数 | Casino IN", "韓国カジノの内国人・外国人利用者数、年度別推移、前年比増減率を確認できます。"),
        "casino_revenue_page": ("韓国カジノの年間売上高・市場シェア | Casino IN", "韓国カジノ各社の年度別売上高、市場シェア、ウォン換算の参考値を比較します。"),
        "casino_fund_page": ("カジノ観光振興開発基金の賦課状況 | Casino IN", "韓国カジノ事業者に対する観光振興開発基金の賦課額と年度別推移を確認できます。"),
        "related_news_page": ("韓国カジノ産業ニュース | Casino IN", "韓国のカジノ、観光、複合リゾート関連ニュースをAI分析、主要論点、原文リンクとともに確認できます。"),
        "overseas_news_page": ("マカオ・日本カジノ海外ニュース | Casino IN", "マカオと日本のカジノ・統合型リゾート関連ニュースを韓国語訳、要約、原文リンク付きで確認できます。"),
        "market_trend_page": ("カジノ企業の株価・時価総額 | Casino IN", "韓国の主要カジノ企業とマカオのゲーミング企業について、株価、指数、時価総額の動きを比較します。"),
        "tourism_trend_page": ("訪韓外国人観光客の統計・分析 | Casino IN", "国・地域別の訪韓外国人旅行者数、月次推移、前年同期比を比較し、カジノ需要の基礎指標を確認します。"),
        "economic_trend_page": ("為替・燃料価格の推移 | Casino IN", "韓国の燃料価格と主要通貨の為替レートを時系列グラフで確認できます。"),
        "holiday_calendar_page": ("アジア主要国の祝日カレンダー | Casino IN", "韓国、中国、日本、台湾、モンゴルなど主要市場の祝日と連休日程を国別に比較します。"),
        "salary_trend_page": ("韓国カジノ業界の年収情報 | Casino IN", "韓国主要カジノ企業の公開平均年収、比較業界の水準、月別変化を確認できます。"),
        "recruitment_page": ("韓国カジノ業界の求人情報 | Casino IN", "韓国の主要求人サイトから収集したカジノ・ホテル・複合リゾート関連の採用情報を確認できます。"),
        "company_recruitment_guide_page": ("カジノ企業の面接・採用ガイド | Casino IN", "企業別の面接質問、実技試験、選考形式、会場の雰囲気など、採用経験に基づく記録を確認できます。"),
        "disclosures_page": ("カジノ企業の開示情報 | Casino IN", "韓国の主要カジノ企業がDARTに提出した開示、提出者、提出日、AI要約をまとめて確認できます。"),
        "laws_page": ("韓国カジノ法令・規制 | Casino IN", "観光振興法、カジノ営業準則などの現行法令、条文、最近の改正履歴を確認できます。"),
        "legislation_page": ("韓国カジノ関連の立法動向 | Casino IN", "政府の立法予告と国会に提出されたカジノ・観光関連法案の発議、審査状況を追跡します。"),
        "companies_page": ("韓国カジノ企業の比較分析 | Casino IN", "パラダイス、GKL、カンウォンランド、ロッテ観光開発について、企業概要、財務、信用格付け、ニュースを比較します。"),
        "company_benefits_page": ("カジノ企業の福利厚生比較 | Casino IN", "韓国カジノ企業の福利厚生制度、支援金額・水準、備考、終了した制度の履歴を企業別に比較します。"),
        "company_news_page": ("カジノ企業別ニュース | Casino IN", "韓国の主要カジノ企業ニュースを企業、重要度、影響、AI分析カテゴリー別に比較します。"),
        "research_library_page": ("カジノ市場レポート・分析資料 | Casino IN", "証券会社レポート、産業調査資料、IR文書、AI分析を通じてカジノ市場の主要論点を確認できます。"),
        "tips.list_page": ("カジノ業務ナレッジ資料室 | Casino IN", "業務自動化、報告書作成、データ分析、カジノ運営に関する公開ガイドと実務ノウハウを提供します。"),
        "tips.sites_page": ("カジノ産業の関連サイト集 | Casino IN", "カジノ産業調査、企業開示、統計、法令、採用、実務に役立つ外部サイトを分野別に紹介します。"),
        "tips.glossary_page": ("カジノ・経営・財務用語集 | Casino IN", "カジノ運営、経営管理、会計、財務、投資分析で使われる用語の英語表記、意味、わかりやすい説明を検索できます。"),
        "credits_page": ("データ出典・著作権 | Casino IN", "Casino INで使用するデータの出典、更新周期、最終確認日時、著作権と利用上の注意を案内します。"),
    },
    "yue-HK": {
        "public_home": ("Casino IN｜賭場產業資訊及分析", "集中查看南韓及海外賭場企業、訪韓旅客、匯率、公司公告、市場走勢、招聘及法規等產業資料。"),
        "casino_industry_page": ("南韓賭場產業概況｜Casino IN", "比較南韓外國人專用賭場及本地人設施的營運公司、地區分布、收入和入場人次。"),
        "casino_visitors_page": ("南韓賭場年度入場人次｜Casino IN", "查看南韓賭場本地及外國旅客的年度入場人次、歷年走勢和按年變化。"),
        "casino_revenue_page": ("南韓賭場年度收入及市佔率｜Casino IN", "比較南韓各賭場的年度收入、市場佔有率及韓圜參考數值。"),
        "casino_fund_page": ("賭場旅遊振興基金徵費｜Casino IN", "查看南韓賭場營運商旅遊振興開發基金的年度徵費金額及變化。"),
        "related_news_page": ("南韓賭場產業新聞｜Casino IN", "查看南韓賭場、旅遊及綜合度假村新聞，並附有AI分析、重點議題及原文連結。"),
        "overseas_news_page": ("澳門及日本賭場新聞｜Casino IN", "追蹤澳門及日本賭場、綜合度假村新聞，提供韓文翻譯、摘要及原文連結。"),
        "market_trend_page": ("賭場企業股價及市值｜Casino IN", "比較南韓主要賭場公司及澳門博彩企業的股價、指數和市值走勢。"),
        "tourism_trend_page": ("訪韓旅客統計及分析｜Casino IN", "按國家及地區比較訪韓外國旅客人數、每月走勢和按年變化，了解賭場需求基礎指標。"),
        "economic_trend_page": ("匯率及燃油價格走勢｜Casino IN", "以時間序列圖表查看南韓燃油價格及主要貨幣匯率變化。"),
        "holiday_calendar_page": ("亞洲主要市場假期日曆｜Casino IN", "比較南韓、中國、日本、台灣、蒙古等主要市場的公眾假期及長假安排。"),
        "salary_trend_page": ("南韓賭場行業薪酬資料｜Casino IN", "查看南韓主要賭場企業公開的平均年薪、比較行業水平及每月變化。"),
        "recruitment_page": ("南韓賭場行業招聘資訊｜Casino IN", "瀏覽由南韓主要招聘平台收集的賭場、酒店及綜合度假村職位空缺。"),
        "company_recruitment_guide_page": ("賭場企業面試及招聘指南｜Casino IN", "查看各企業的面試問題、實務測試、招聘流程及現場氣氛等求職經驗紀錄。"),
        "disclosures_page": ("賭場企業公告資料｜Casino IN", "集中查看南韓主要賭場企業提交至DART的公司公告、提交人、日期及AI摘要。"),
        "laws_page": ("南韓賭場法例及監管｜Casino IN", "查看《觀光振興法》、賭場營業準則等現行法例、條文及近期修訂紀錄。"),
        "legislation_page": ("南韓賭場立法動向｜Casino IN", "追蹤政府立法預告及國會提出的賭場、旅遊相關法案和審議進度。"),
        "companies_page": ("南韓賭場企業比較分析｜Casino IN", "比較Paradise、GKL、江原樂園及樂天觀光開發的公司概況、財務、信貸評級和新聞。"),
        "company_benefits_page": ("賭場企業員工福利比較｜Casino IN", "比較南韓賭場企業的員工福利、津貼金額或水平、備註及已終止福利的紀錄。"),
        "company_news_page": ("賭場企業分類新聞｜Casino IN", "按公司、重要程度、影響及AI分析分類，比較南韓主要賭場企業新聞。"),
        "research_library_page": ("賭場市場報告及分析資料｜Casino IN", "查看證券行報告、產業研究、投資者關係文件及AI分析，掌握賭場市場重點。"),
        "tips.list_page": ("賭場工作知識資料庫｜Casino IN", "提供工作自動化、報告製作、數據分析及賭場營運相關的公開指南和實務知識。"),
        "tips.sites_page": ("賭場產業相關網站｜Casino IN", "按類別整理賭場產業研究、公司公告、統計、法例、招聘及工作所需的外部網站。"),
        "tips.glossary_page": ("賭場、管理及財務詞彙表｜Casino IN", "搜尋賭場營運、企業管理、會計、財務及投資分析常用詞彙的英文名稱、意思和簡單解釋。"),
        "credits_page": ("資料來源及版權｜Casino IN", "說明Casino IN使用的資料來源、更新周期、最後核實時間、版權及使用注意事項。"),
    },
}
