import * as React from "react";
import { useEffect, useRef } from "react";

export interface BlackHoleHeroSectionProps extends React.HTMLAttributes<HTMLDivElement>{distance?:number;elevation?:number;azimuth?:number;orbitSpeed?:number;roll?:number;fov?:number;diskInner?:number;diskOuter?:number;diskThickness?:number;diskDensity?:number;brightness?:number;spinSpeed?:number;grain?:number;doppler?:number;hotColor?:string;midColor?:string;coolColor?:string;starBrightness?:number;glow?:number;exposure?:number;vignette?:number;steps?:number;resolution?:number;maxDpr?:number;focus?:[number,number];scrim?:"none"|"left"|"right"|"top"|"bottom";scrimStrength?:number;paused?:boolean;children?:React.ReactNode}

const VERT=`attribute vec2 aPos;varying vec2 vUv;void main(){vUv=aPos*.5+.5;gl_Position=vec4(aPos,0.,1.);}`;
const SCENE_FRAG=`
precision highp float;
#define MAX_STEPS 460
#define WIND_CYCLE 46.0
varying vec2 vUv;
uniform vec2 uRes,uFocus,uJitter;uniform float uTime,uTanHalf,uSteps,uSkyR,uDiskIn,uDiskOut,uThick,uDensity,uSpin,uGrain,uBright,uDoppler,uStars,uEncode,uSeed;uniform vec3 uCamPos,uRight,uUp,uFwd,uHot,uMid,uCool;
float hash13(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float vnoise(vec3 x){vec3 i=floor(x),f=fract(x);f=f*f*(3.-2.*f);return mix(mix(mix(hash13(i),hash13(i+vec3(1,0,0)),f.x),mix(hash13(i+vec3(0,1,0)),hash13(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash13(i+vec3(0,0,1)),hash13(i+vec3(1,0,1)),f.x),mix(hash13(i+vec3(0,1,1)),hash13(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p,float lod){float a=.5,s=0.;for(int i=0;i<4;i++){s+=(i==3?a*lod:a)*vnoise(p);p=p*2.03+vec3(11.3,7.1,3.7);a*=.5;}return s;}
void gasAt(vec3 p,float rd,float dt,out float dens,out vec3 tint,out float heat){float rn=clamp((rd-uDiskIn)/max(.001,uDiskOut-uDiskIn),0.,1.);float tk=uThick*(.35+1.25*rn);float sheet=exp(-pow(p.y/tk,2.));float lod=clamp(1.-dt*uGrain*14.,0.,1.);float phi=atan(p.z,p.x);float omega=uSpin*pow(uDiskIn/rd,1.5);float lr=log(rd)*1.1+uSpin*uTime*.05;float u=uTime/WIND_CYCLE,fA=fract(u),fB=fract(u+.5),w=abs(2.*fA-1.);float cA=fbm(vec3(vec2(cos(phi+omega*fA*WIND_CYCLE),sin(phi+omega*fA*WIND_CYCLE))*(rd*uGrain),lr),lod);float cB=fbm(vec3(vec2(cos(phi+omega*fB*WIND_CYCLE),sin(phi+omega*fB*WIND_CYCLE))*(rd*uGrain),lr+40.),lod);float clouds=mix(cA,cB,w);float fil=clouds*clouds*1.75;float inner=smoothstep(0.,.07,rn),outer=1.-smoothstep(.45,1.,rn);float prof=inner*outer*pow(uDiskIn/rd,2.);dens=max(0.,fil*1.5-.30)*sheet*prof*uDensity*4.6;heat=pow(uDiskIn/rd,.8)*(.72+.55*clouds);tint=mix(uCool,uMid,smoothstep(.10,.52,heat));tint=mix(tint,uHot,smoothstep(.52,1.05,heat));}
vec3 starField(vec3 d){vec3 a=abs(d);vec2 uv;float face;if(a.x>=a.y&&a.x>=a.z){uv=d.yz/a.x;face=d.x>0.?0.:1.;}else if(a.y>=a.z){uv=d.xz/a.y;face=d.y>0.?2.:3.;}else{uv=d.xy/a.z;face=d.z>0.?4.:5.;}vec3 col=vec3(0.);for(int k=0;k<3;k++){float sc=90.*pow(2.2,float(k));vec2 p=uv*sc,id=floor(p),f=fract(p)-.5;float h=hash13(vec3(id,face*19.));if(h>.965){vec2 off=vec2(hash13(vec3(id,face+11.)),hash13(vec3(id,face+23.)));float s=smoothstep(.055,0.,length(f-(off-.5)*.7));col+=s*(.6+4.5*fract(h*97.))*mix(vec3(.72,.82,1.),vec3(1.,.88,.72),hash13(vec3(id,face+51.)))/pow(2.2,float(k));}}return col+vec3(.013,.017,.03)*fbm(d*2.6,1.);}
void main(){vec2 uv=(gl_FragCoord.xy+uJitter-uFocus*uRes)/uRes.y;vec3 dir=normalize(uFwd+(uv.x*uRight+uv.y*uUp)*2.*uTanHalf),pos=uCamPos,vel=dir;vec3 hv=cross(pos,vel);float h2=dot(hv,hv),h=sqrt(h2),swept=0.,transmit=1.;vec3 col=vec3(0.);bool captured=false;float jitter=fract(sin(dot(gl_FragCoord.xy+uSeed,vec2(12.9898,78.233)))*43758.5453);
for(int i=0;i<MAX_STEPS;i++){if(float(i)>=uSteps)break;float r2=dot(pos,pos),r=sqrt(r2);if(r<1.){captured=true;break;}if(r>uSkyR&&dot(pos,vel)>0.)break;if(transmit<.004)break;float dt=clamp(.14*(r-1.),.025,1.1);if(r<uDiskOut*1.25){float rn=clamp((r-uDiskIn)/max(.001,uDiskOut-uDiskIn),0.,1.),tk=uThick*(.35+1.25*rn);dt=min(dt,max(tk*.38,abs(pos.y)*.5));}swept+=h*dt/r2;float deep=exp(-1.3*max(0.,swept-4.6));jitter=fract(jitter+.6180339887);vec3 mid=pos+vel*(dt*jitter);float rd=length(mid.xz);if(rd>uDiskIn&&rd<uDiskOut&&abs(mid.y)<uThick*5.){float dens,heat;vec3 tint;gasAt(mid,rd,dt,dens,tint,heat);if(dens>.001){vec3 tang=normalize(cross(vec3(0,1,0),vec3(mid.x,0,mid.z)));float beta=min(.85,sqrt(.5/max(rd,1.5))),gam=inversesqrt(max(.0001,1.-beta*beta));float g=1./(gam*(1.-beta*dot(tang,-normalize(vel))));g*=sqrt(max(.05,1.-1./rd));float boost=pow(max(g,.02),3.*uDoppler);vec3 shift=mix(vec3(1),g>1.?vec3(.86,.94,1.14):vec3(1.15,.82,.62),clamp(abs(g-1.)*1.6,0.,1.)*uDoppler);col+=tint*shift*(uBright*(.26+2.*heat*heat)*boost*dens*transmit*dt*deep);transmit*=exp(-dens*.30*dt);}}vec3 acc=-1.5*h2*pos/(r2*r2*r);vel+=acc*dt;pos+=vel*dt;}
if(!captured&&uStars>.001){vec3 toHole=normalize(-uCamPos);float stretch=clamp(length(cross(normalize(dir),toHole))/max(.001,length(cross(normalize(vel),toHole))),1.,40.);col+=starField(normalize(vel))*uStars*transmit/stretch;}if(uEncode>.5)col=col/(1.+col);gl_FragColor=vec4(col,1.);}`;
const BLEND_FRAG=`precision highp float;varying vec2 vUv;uniform sampler2D uCur,uPrev;uniform float uAlpha;void main(){gl_FragColor=vec4(mix(texture2D(uPrev,vUv).rgb,texture2D(uCur,vUv).rgb,uAlpha),1.);}`;
const BRIGHT_FRAG=`precision highp float;varying vec2 vUv;uniform sampler2D uTex;uniform vec2 uTexel;uniform float uDecode,uPack,uThreshold;void main(){vec3 s=(texture2D(uTex,vUv+uTexel*vec2(-1,-1)).rgb+texture2D(uTex,vUv+uTexel*vec2(1,-1)).rgb+texture2D(uTex,vUv+uTexel*vec2(-1,1)).rgb+texture2D(uTex,vUv+uTexel).rgb)*.25;if(uDecode>.5)s=s/max(vec3(.002),1.-s);float l=max(s.r,max(s.g,s.b));s*=max(0.,l-uThreshold)/max(.0001,l);gl_FragColor=vec4(s*uPack,1.);}`;
const BLUR_FRAG=`precision highp float;varying vec2 vUv;uniform sampler2D uTex;uniform vec2 uStep;void main(){vec3 s=texture2D(uTex,vUv).rgb*.227027;s+=(texture2D(uTex,vUv+uStep*1.3846154).rgb+texture2D(uTex,vUv-uStep*1.3846154).rgb)*.3162162;s+=(texture2D(uTex,vUv+uStep*3.2307692).rgb+texture2D(uTex,vUv-uStep*3.2307692).rgb)*.0702702;gl_FragColor=vec4(s,1.);}`;
const COMPOSITE_FRAG=`precision highp float;varying vec2 vUv;uniform sampler2D uScene,uBloom;uniform float uDecode,uPack,uGlow,uExposure,uVignette,uScrimDir,uScrimAmt,uSeed;vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}void main(){vec3 scene=texture2D(uScene,vUv).rgb;if(uDecode>.5)scene=scene/max(vec3(.002),1.-scene);vec3 c=aces((scene+texture2D(uBloom,vUv).rgb/uPack*uGlow)*uExposure);c=pow(max(c,0.),vec3(.4545));vec2 d=vUv-.5;c*=1.-uVignette*dot(d,d)*1.9;if(uScrimDir>.5){float x=uScrimDir<1.5?vUv.x:uScrimDir<2.5?1.-vUv.x:uScrimDir<3.5?1.-vUv.y:vUv.y;c*=1.-uScrimAmt*pow(1.-clamp(x,0.,1.),2.4);}float n=fract(sin(dot(gl_FragCoord.xy+uSeed,vec2(12.9898,78.233)))*43758.5453);gl_FragColor=vec4(c+(n-.5)/255.,1.);}`;

const RAD=Math.PI/180;
function linear(hex:string){const h=hex.replace("#","");const n=parseInt(h.length===3?h.split("").map(x=>x+x).join(""):h.slice(0,6),16);return [16,8,0].map(s=>{const v=((n>>s)&255)/255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);});}
type Prog={program:WebGLProgram;u:Record<string,WebGLUniformLocation|null>};type Target={fb:WebGLFramebuffer;tex:WebGLTexture;w:number;h:number};

export function BlackHoleHeroSection({distance=24,elevation=-5.5,azimuth=0,orbitSpeed=0,roll=-20,fov=42,diskInner=3,diskOuter=15,diskThickness=.26,diskDensity=1,brightness=1,spinSpeed=.06,grain=.48,doppler=.35,hotColor="#FFF3DE",midColor="#FF9838",coolColor="#8E3A0B",starBrightness=0,glow=1,exposure=.9,vignette=.28,steps=300,resolution=.7,maxDpr=1.75,focus=[.72,.46],scrim="none",scrimStrength=.9,paused=false,className="",children,...rest}:BlackHoleHeroSectionProps){
const hostRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null);const props=useRef({distance,elevation,azimuth,orbitSpeed,roll,fov,diskInner,diskOuter,diskThickness,diskDensity,brightness,spinSpeed,grain,doppler,hotColor,midColor,coolColor,starBrightness,glow,exposure,vignette,steps,resolution,maxDpr,focus,scrim,scrimStrength,paused});props.current={distance,elevation,azimuth,orbitSpeed,roll,fov,diskInner,diskOuter,diskThickness,diskDensity,brightness,spinSpeed,grain,doppler,hotColor,midColor,coolColor,starBrightness,glow,exposure,vignette,steps,resolution,maxDpr,focus,scrim,scrimStrength,paused};
useEffect(()=>{const host=hostRef.current,canvas=canvasRef.current;if(!host||!canvas)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const gl=(canvas.getContext("webgl2",{alpha:false,antialias:false,depth:false,stencil:false,powerPreference:"high-performance"})||canvas.getContext("webgl",{alpha:false,antialias:false,depth:false,stencil:false,powerPreference:"high-performance"})) as WebGLRenderingContext|null;if(!gl){host.dataset.webgl="unsupported";canvas.hidden=true;return;}const dbg=gl.getExtension("WEBGL_debug_renderer_info") as {UNMASKED_RENDERER_WEBGL:number}|null;const renderer=dbg?String(gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL)):"";const software=/swiftshader|llvmpipe|softpipe|software|microsoft basic/i.test(renderer);const isGL2=typeof WebGL2RenderingContext!=="undefined"&&gl instanceof WebGL2RenderingContext;
let running=true,visible=true,raf=0,clock=reduced?6:0,last=0,settled=0,w=0,h=0,sw=0,sh=0;let sceneProg:Prog,blendProg:Prog,brightProg:Prog,blurProg:Prog,compProg:Prog,vbo:WebGLBuffer|null=null;let scene:Target|null=null,histA:Target|null=null,histB:Target|null=null,bloomA:Target|null=null,bloomB:Target|null=null;let hdr=true;let texType:number=gl.UNSIGNED_BYTE,internal:number=gl.RGBA,textureFilter:number=gl.LINEAR;
const compile=(type:number,src:string)=>{const s=gl.createShader(type);if(!s)throw Error("shader");gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||"shader compile");return s;};
const link=(frag:string):Prog=>{const vs=compile(gl.VERTEX_SHADER,VERT),fs=compile(gl.FRAGMENT_SHADER,frag),program=gl.createProgram();if(!program)throw Error("program");gl.attachShader(program,vs);gl.attachShader(program,fs);gl.bindAttribLocation(program,0,"aPos");gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||"link");const u:Record<string,WebGLUniformLocation|null>={};for(let i=0;i<Number(gl.getProgramParameter(program,gl.ACTIVE_UNIFORMS));i++){const x=gl.getActiveUniform(program,i);if(x)u[x.name]=gl.getUniformLocation(program,x.name);}return{program,u};};
const drop=()=>{for(const t of [scene,histA,histB,bloomA,bloomB])if(t){gl.deleteTexture(t.tex);gl.deleteFramebuffer(t.fb);}scene=histA=histB=bloomA=bloomB=null;settled=0;};
const makeTarget=(tw:number,th:number):Target=>{const tex=gl.createTexture(),fb=gl.createFramebuffer();if(!tex||!fb)throw Error("framebuffer");gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,internal,tw,th,0,gl.RGBA,texType,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,textureFilter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,textureFilter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error("framebuffer incomplete");return{fb,tex,w:tw,h:th};};
const build=()=>{sceneProg=link(SCENE_FRAG);blendProg=link(BLEND_FRAG);brightProg=link(BRIGHT_FRAG);blurProg=link(BLUR_FRAG);compProg=link(COMPOSITE_FRAG);vbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);};
if(isGL2&&((gl as WebGL2RenderingContext).getExtension("EXT_color_buffer_half_float")||(gl as WebGL2RenderingContext).getExtension("EXT_color_buffer_float"))){texType=(gl as WebGL2RenderingContext).HALF_FLOAT;internal=(gl as WebGL2RenderingContext).RGBA16F;}else if(!isGL2){const half=gl.getExtension("OES_texture_half_float") as {HALF_FLOAT_OES:number}|null;const color=gl.getExtension("EXT_color_buffer_half_float");if(half&&color){texType=half.HALF_FLOAT_OES;textureFilter=gl.getExtension("OES_texture_half_float_linear")?gl.LINEAR:gl.NEAREST;}else hdr=false;}else hdr=false;const pack=hdr?1:.12;
const resize=()=>{const r=host.getBoundingClientRect(),dpr=software?1:Math.min(devicePixelRatio||1,Math.max(1,props.current.maxDpr)),scale=software?.34:Math.min(1,Math.max(.4,props.current.resolution));const nw=Math.max(2,Math.round(r.width*dpr)),nh=Math.max(2,Math.round(r.height*dpr)),nsw=Math.max(2,Math.round(nw*scale)),nsh=Math.max(2,Math.round(nh*scale));if(nw===w&&nh===h&&nsw===sw&&nsh===sh)return;w=nw;h=nh;sw=nsw;sh=nsh;canvas.width=w;canvas.height=h;drop();scene=makeTarget(sw,sh);histA=makeTarget(sw,sh);histB=makeTarget(sw,sh);bloomA=makeTarget(Math.max(2,sw>>2),Math.max(2,sh>>2));bloomB=makeTarget(Math.max(2,sw>>2),Math.max(2,sh>>2));};
const pass=(p:Prog,t:Target|null)=>{gl.useProgram(p.program);gl.bindFramebuffer(gl.FRAMEBUFFER,t?t.fb:null);gl.viewport(0,0,t?t.w:w,t?t.h:h);};const draw=()=>gl.drawArrays(gl.TRIANGLES,0,3);const bind=(tex:WebGLTexture,n:number)=>{gl.activeTexture(gl.TEXTURE0+n);gl.bindTexture(gl.TEXTURE_2D,tex);};const halton:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[.5,.333],[.25,.667],[.75,.111],[.125,.444],[.625,.778],[.375,.222],[.875,.556],[.0625,.889]];
const render=(t:number)=>{if(!scene||!histA||!histB||!bloomA||!bloomB)return;const C=props.current,az=(C.azimuth+C.orbitSpeed*t)*RAD,el=Math.max(-88,Math.min(88,C.elevation))*RAD,dist=Math.max(2.2,C.distance),ce=Math.cos(el),cx=dist*ce*Math.cos(az),cy=dist*Math.sin(el),cz=dist*ce*Math.sin(az),fx=-cx/dist,fy=-cy/dist,fz=-cz/dist;let rx=fz,ry=0,rz=-fx;const rl=Math.hypot(rx,ry,rz)||1;rx/=rl;ry/=rl;rz/=rl;const ux=ry*fz-rz*fy,uy=rz*fx-rx*fz,uz=rx*fy-ry*fx,cr=Math.cos(C.roll*RAD),sr=Math.sin(C.roll*RAD),RX=rx*cr+ux*sr,RY=ry*cr+uy*sr,RZ=rz*cr+uz*sr,UX=-rx*sr+ux*cr,UY=-ry*sr+uy*cr,UZ=-rz*sr+uz*cr,hot=linear(C.hotColor),mid=linear(C.midColor),cool=linear(C.coolColor),outer=Math.max(C.diskInner+.5,C.diskOuter);
pass(sceneProg,scene);const u=sceneProg.u;gl.uniform2f(u.uRes,scene.w,scene.h);gl.uniform1f(u.uTime,t);gl.uniform3f(u.uCamPos,cx,cy,cz);gl.uniform3f(u.uRight,RX,RY,RZ);gl.uniform3f(u.uUp,UX,UY,UZ);gl.uniform3f(u.uFwd,fx,fy,fz);gl.uniform1f(u.uTanHalf,Math.tan(Math.max(8,Math.min(110,C.fov))*.5*RAD));gl.uniform2f(u.uFocus,C.focus[0],1-C.focus[1]);gl.uniform1f(u.uSteps,software?130:Math.max(60,Math.min(460,Math.round(C.steps))));gl.uniform1f(u.uSkyR,Math.max(dist*1.35,outer*2.4));gl.uniform1f(u.uDiskIn,Math.max(1.05,C.diskInner));gl.uniform1f(u.uDiskOut,outer);gl.uniform1f(u.uThick,Math.max(.02,C.diskThickness));gl.uniform1f(u.uDensity,Math.max(0,C.diskDensity));gl.uniform1f(u.uSpin,C.spinSpeed*6.2831853);gl.uniform1f(u.uGrain,Math.max(.02,C.grain));gl.uniform1f(u.uBright,Math.max(0,C.brightness));gl.uniform1f(u.uDoppler,Math.max(0,Math.min(1,C.doppler)));gl.uniform3f(u.uHot,hot[0],hot[1],hot[2]);gl.uniform3f(u.uMid,mid[0],mid[1],mid[2]);gl.uniform3f(u.uCool,cool[0],cool[1],cool[2]);gl.uniform1f(u.uStars,Math.max(0,C.starBrightness));gl.uniform1f(u.uEncode,hdr?0:1);const j=halton[settled%halton.length];gl.uniform2f(u.uJitter,j[0]-.5,j[1]-.5);gl.uniform1f(u.uSeed,(settled%64)*17.13);draw();
pass(blendProg,histB);bind(scene.tex,0);bind(histA.tex,1);gl.uniform1i(blendProg.u.uCur,0);gl.uniform1i(blendProg.u.uPrev,1);gl.uniform1f(blendProg.u.uAlpha,settled? .14:1);draw();const shown=histB;[histA,histB]=[histB,histA];settled++;pass(brightProg,bloomA);bind(shown.tex,0);gl.uniform1i(brightProg.u.uTex,0);gl.uniform2f(brightProg.u.uTexel,1/shown.w,1/shown.h);gl.uniform1f(brightProg.u.uDecode,hdr?0:1);gl.uniform1f(brightProg.u.uPack,pack);gl.uniform1f(brightProg.u.uThreshold,.85);draw();const blur=(a:Target,b:Target,x:number,y:number)=>{pass(blurProg,b);bind(a.tex,0);gl.uniform1i(blurProg.u.uTex,0);gl.uniform2f(blurProg.u.uStep,x/b.w,y/b.h);draw();};blur(bloomA,bloomB,1,0);blur(bloomB,bloomA,0,1);blur(bloomA,bloomB,2.6,0);blur(bloomB,bloomA,0,2.6);pass(compProg,null);bind(shown.tex,0);bind(bloomA.tex,1);gl.uniform1i(compProg.u.uScene,0);gl.uniform1i(compProg.u.uBloom,1);gl.uniform1f(compProg.u.uDecode,hdr?0:1);gl.uniform1f(compProg.u.uPack,pack);gl.uniform1f(compProg.u.uGlow,Math.max(0,C.glow)*.26);gl.uniform1f(compProg.u.uExposure,Math.max(.05,C.exposure));gl.uniform1f(compProg.u.uVignette,Math.max(0,Math.min(1,C.vignette)));gl.uniform1f(compProg.u.uScrimDir,C.scrim==="left"?1:C.scrim==="right"?2:C.scrim==="top"?3:C.scrim==="bottom"?4:0);gl.uniform1f(compProg.u.uScrimAmt,Math.max(0,Math.min(1,C.scrimStrength)));gl.uniform1f(compProg.u.uSeed,(t*60)%1000);draw();};
try{build();resize();host.dataset.webgl="ready";for(let i=0;i<(reduced?12:1);i++)render(clock);}catch(e){host.dataset.webgl="failed";canvas.hidden=true;console.error("blackhole hero initialization failed",e);return;}const tick=(now:number)=>{if(!running)return;raf=requestAnimationFrame(tick);if(!visible){last=now;return;}const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!props.current.paused&&!reduced)clock+=dt;render(clock);};if(!reduced)raf=requestAnimationFrame(tick);const ro=new ResizeObserver(()=>{resize();if(reduced||props.current.paused)for(let i=0;i<8;i++)render(clock);});ro.observe(host);const io=new IntersectionObserver(e=>{visible=e[0]?.isIntersecting??true;});io.observe(host);const visibility=()=>{visible=!document.hidden;last=0;};const lost=(e:Event)=>{e.preventDefault();running=false;cancelAnimationFrame(raf);canvas.hidden=true;host.dataset.webgl="lost";};const restored=()=>{try{w=h=sw=sh=0;build();resize();canvas.hidden=false;host.dataset.webgl="restored";running=true;last=0;for(let i=0;i<(reduced?12:1);i++)render(clock);if(!reduced)raf=requestAnimationFrame(tick);}catch(e){host.dataset.webgl="restore-failed";canvas.hidden=true;console.error("blackhole hero restoration failed",e);}};document.addEventListener("visibilitychange",visibility);canvas.addEventListener("webglcontextlost",lost);canvas.addEventListener("webglcontextrestored",restored);return()=>{running=false;cancelAnimationFrame(raf);ro.disconnect();io.disconnect();document.removeEventListener("visibilitychange",visibility);canvas.removeEventListener("webglcontextlost",lost);canvas.removeEventListener("webglcontextrestored",restored);drop();if(vbo)gl.deleteBuffer(vbo);for(const p of [sceneProg,blendProg,brightProg,blurProg,compProg])if(p)gl.deleteProgram(p.program);};},[]);
return <div ref={hostRef} className={`blackhole-renderer ${className}`} {...rest}><canvas ref={canvasRef} aria-hidden="true"/><div className="blackhole-renderer-content">{children}</div></div>;
}
export default BlackHoleHeroSection;
